### ISSUE TITLE
To do to get ready for GF

### ISSUE THREAD

**Issue by RosaWagner** [kosmynkab/Poltawski-Nowy#1]
@kosmynkab the following needs your attention before I can make the build the font ;)

- [x] Add Medium instance (might need to review location of SemiBold so it is consistent)
- [x] Add `IJ` and `ij` (as normal composite, just to have the codepoint for backward compatibility)
- [x] Set the spacing of `periodcentered.loclCAT` so  `/l /periodcentered.loclCAT /l` behaves like `/ldot /l`
- [x] Add `periodcentered.loclCAT.case` and set the spacing so `/L /periodcentered.loclCAT.case /L` behaves like `/Ldot /L`

Then I will be able to:

- correct the copyright strings and other metadata
- correct style linking bits and weightClass
- adjust vertical metrics
- export the font

I know that adding a medium instance can be annoying, the reason is explained here: https://googlefonts.github.io/gf-guide/variable.html#instantiated-static-fonts

Let me know when I can continue :)

**Comment by kosmynkab** [comment]
Should all be sorted now! Took us a moment ;)
